### ISSUE TITLE
Generate release header is freezing on macOS

### ISSUE THREAD

**Issue by paulocoutinhox** [google/jni-bind#230]
Hi,

When i try run "" it is freezing or stopping somewhere and nothing happen.

```
paulo ~/Developer/workspaces/cpp  $ git clone https://github.com/google/jni-bind.git
Cloning into 'jni-bind'...
remote: Enumerating objects: 2983, done.
remote: Counting objects: 100% (684/684), done.
remote: Compressing objects: 100% (226/226), done.
remote: Total 2983 (delta 474), reused 511 (delta 425), pack-reused 2299
Receiving objects: 100% (2983/2983), 1.12 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (2174/2174), done.
paulo ~/Developer/workspaces/cpp  $ cd jni-bind 
paulo ~/Developer/workspaces/cpp/jni-bind [main] $ ./build_jni_bind_release.sh     <--- it freeze here and do nothing
```

Im using macOS Ventura with M1.

Thanks.

**Comment by jwhpryor** [comment]
Actually, that script is invoked through a genrule and isn't meant to be called directly.  It takes arguments and will freeze if none are passed.  The behaviour is actually WAII because you don't have any arguments.

Unfortunately, because of a bug in Bazel, it failed to work on the public version.  Since I was the only person who releases the project, I just removed it from the public version to make progress. 

I took a brief stab at reintroducing it, but it wasn't trivial.  I'll take another look.  Sorry that it's got the confusing name that it has.

**Comment by paulocoutinhox** [comment]
Do you have any script (shell, python, etc) that i can generate the single header file?

**Comment by jwhpryor** [comment]
Yes, and in fact, this is the script, it just requires arguments.  Typically those arguments are passed in through a genrule.  

The freezing behaviour you're seeing is actually WAII.  I'll try taking another pass at making the release targets public.
